spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: loan-service
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/loan/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8088
